# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
