# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_test_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_date',
        ),
    ]
