# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170921_1451'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AfterParty',
        ),
    ]
