# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_delete_afterparty'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='location', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='score_k',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='score_y',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
