# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170921_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AddField(
            model_name='post',
            name='location_howto',
            field=models.CharField(default='location', max_length=200),
        ),
    ]
