# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-21 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_afterparty_cheeringsongs_score_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='score',
            name='message',
        ),
    ]
